opensocsysarch/CoreGen

- include/CoreGen/StoneCutter/SCOpts.h
- src/StoneCutter/SCOpts.cpp
- test/CMakeLists.txt
- test/StoneCutter/CLI/CMakeLists.txt
- test/StoneCutter/CLI/sccomp_help.sh
- test/StoneCutter/CLI/sccomp_help_KF.sh
- test/StoneCutter/CLI/sccomp_keep.sh
- test/StoneCutter/CLI/sccomp_noopt.sh
- test/StoneCutter/CLI/sccomp_opt.sh
- test/StoneCutter/CLI/sccomp_parse.sh
- test/StoneCutter/CLI/sccomp_verbose.sh
- test/StoneCutter/CLI/sccomp_version.sh
- test/StoneCutter/CMakeLists.txt
This cleans up the help menu interface for the 'sccomp' tool.  It also adds tests for the current set of CLI options.
> Merging up changes in SCComp CLI help menus and associated tests

- include/CoreGen/StoneCutter/SCLexer.h
- include/CoreGen/StoneCutter/SCParser.h
- src/StoneCutter/SCLexer.cpp
- src/StoneCutter/SCParser.cpp
Adding initial StoneCutter language support for conditionals and loops
> StoneCutter syntax support for conditionals & loops

- README.md
- include/CoreGen/CoreGenBackend/CoreGenBackend.h
- include/CoreGen/CoreGenBackend/CoreGenDAG.h
- include/CoreGen/CoreGenBackend/CoreGenPass.h
- include/CoreGen/CoreGenBackend/CoreGenPassMgr.h
- include/CoreGen/CoreGenBackend/Passes/Analysis/ASPSolverPass.h
- include/CoreGen/CoreGenBackend/Passes/CoreGenPasses.h
- include/CoreGen/StoneCutter/SCParser.h
- src/CGCLI/CGCLIMain.cpp
- src/CGCLI/CGCLIOpts.cpp
- src/CGCLI/CGCLIOpts.h
- src/CoreGenBackend/CoreGenBackend.cpp
- src/CoreGenBackend/CoreGenPassMgr.cpp
- src/CoreGenBackend/CoreGenYaml.cpp
- src/CoreGenBackend/Passes/Analysis/ASPSolverPass.cpp
- src/CoreGenBackend/Passes/Analysis/CMakeLists.txt
- src/CoreGenBackend/Passes/Analysis/CacheLevelPass.cpp
- src/StoneCutter/SCOpts.cpp
- src/StoneCutter/SCParser.cpp
- test/CGCLI/cgcli_opt_ASP_Single.sh
- test/StoneCutter/Parser/KnownPass/sc_parser_test10.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test11.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test12.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test13.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test14.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test15.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test7.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test8.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test9.sc
Merging changes for StoneCutter syntax and ASP Solver Pass.  This includes all the necessary test facilities to verify these.
> Merging changes for StoneCutter syntax and ASP Solver Pass

- README.md
- include/CoreGen/CoreGenCodegen/CoreGenChiselCodegen.h
- include/CoreGen/CoreGenCodegen/CoreGenCodegen.h
- include/CoreGen/CoreGenCodegen/CoreGenLLVMCodegen.h
- include/CoreGen/StoneCutter/SCChiselCodeGen.h
- src/CoreGenCodegen/CMakeLists.txt
- src/CoreGenCodegen/CoreGenChiselCodegen.cpp
- src/CoreGenCodegen/CoreGenCodegen.cpp
- src/CoreGenCodegen/CoreGenLLVMCodegen.cpp
- src/StoneCutter/SCChiselCodeGen.cpp
- src/StoneCutter/SCExec.cpp
- src/StoneCutter/SCOpts.cpp
- test/StoneCutter/CLI/sccomp_chisel_outfile.sh
- test/StoneCutter/Parser/KnownPass/MultiFile/CMakeLists.txt
- test/StoneCutter/Parser/KnownPass/MultiFile/sc_parser_test1.sc
- test/StoneCutter/Parser/KnownPass/MultiFile/sc_parser_test10.sc
- test/StoneCutter/Parser/KnownPass/MultiFile/sc_parser_test2.sc
- test/StoneCutter/Parser/KnownPass/MultiFile/sc_parser_test3.sc
- test/StoneCutter/Parser/KnownPass/MultiFile/sc_parser_test4.sc
- test/StoneCutter/Parser/KnownPass/MultiFile/sc_parser_test5.sc
- test/StoneCutter/Parser/KnownPass/MultiFile/sc_parser_test6.sc
- test/StoneCutter/Parser/KnownPass/MultiFile/sc_parser_test7.sc
- test/StoneCutter/Parser/KnownPass/MultiFile/sc_parser_test8.sc
- test/StoneCutter/Parser/KnownPass/MultiFile/sc_parser_test9.sc
- test/StoneCutter/Parser/KnownPass/MultiFile/sc_parser_test_MF1.sh
- test/StoneCutter/Parser/KnownPass/MultiFile/sc_parser_test_MF2.sh
- test/StoneCutter/Parser/KnownPass/MultiFile/sc_parser_test_MF3.sh
updates for chisel code generation and support for multiple file inputs for stonecutter compiler
> updates for chisel code generation and stonecutter multi-file support

- include/CoreGen/StoneCutter/Passes/SCInstArg.h
- include/CoreGen/StoneCutter/Passes/SCInstFormat.h
- include/CoreGen/StoneCutter/Passes/SCPipeBuilder.h
- include/CoreGen/StoneCutter/SCChiselCodeGen.h
- include/CoreGen/StoneCutter/SCLexer.h
- include/CoreGen/StoneCutter/SCPass.h
- include/CoreGen/StoneCutter/SCPasses.h
- src/StoneCutter/Passes/CMakeLists.txt
- src/StoneCutter/Passes/SCInstArg.cpp
- src/StoneCutter/Passes/SCInstFormat.cpp
- src/StoneCutter/Passes/SCPipeBuilder.cpp
- src/StoneCutter/SCChiselCodeGen.cpp
- src/StoneCutter/SCExec.cpp
- src/StoneCutter/SCLexer.cpp
- src/StoneCutter/SCParser.cpp
- src/StoneCutter/SCPass.cpp
- test/StoneCutter/CLI/sccomp_verbose2.sh
- test/StoneCutter/CodeGen/KnownPass/sc_codegen_test.sh
- test/StoneCutter/CodeGen/KnownPass/sc_codegen_test_4.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test116.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test117.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test118.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test119.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test120.sc
Minor fixes to variable parsing; adding support for negative numbers; adding while/do-while loops
> Minor fixes to variable parsing; adding support for negative numbers; adding while/do-while loops

- include/CoreGen/CoreGenBackend/CoreGenUtil.h
- include/CoreGen/CoreGenCodegen/CoreGenNodeCodegen.h
- include/CoreGen/CoreGenCodegen/NodeCodegen/RegClassCG.h
- src/CoreGenCodegen/CoreGenChiselCodegen.cpp
- src/CoreGenCodegen/NodeCodegen/RegClassCG.cpp
This includes support for writing the entire register class block for the target device.
> Full Register Class codegen support

- include/CoreGen/CoreGenBackend/CoreGenRegClass.h
- include/CoreGen/CoreGenCodegen/CoreGenChiselCodegen.h
- include/CoreGen/CoreGenCodegen/CoreGenCodegen.h
- include/CoreGen/CoreGenCodegen/CoreGenNodeCodegen.h
- include/CoreGen/CoreGenCodegen/CoreGenNodeCodegens.h
- include/CoreGen/CoreGenCodegen/NodeCodegen/RegClassCG.h
- include/CoreGen/CoreGenCodegen/NodeCodegen/SocCG.h
- include/CoreGen/CoreGenCodegen/NodeCodegen/SpadCG.h
- src/CoreGenBackend/CoreGenRegClass.cpp
- src/CoreGenCodegen/CMakeLists.txt
- src/CoreGenCodegen/CoreGenChiselCodegen.cpp
- src/CoreGenCodegen/CoreGenCodegen.cpp
- src/CoreGenCodegen/CoreGenNodeCodegen.cpp
- src/CoreGenCodegen/NodeCodegen/CMakeLists.txt
- src/CoreGenCodegen/NodeCodegen/RegClassCG.cpp
- src/CoreGenCodegen/NodeCodegen/SocCG.cpp
- src/CoreGenCodegen/NodeCodegen/SpadCG.cpp
Adding support for top-level code generation.  This includes: 
- SoC code generation
- top-level scala files
- register classes
- common configuration files
> Adding support for top-level code generation

- include/CoreGen/CoreGenCodegen/CoreGenChiselCodegen.h
- include/CoreGen/CoreGenCodegen/CoreGenNodeCodegens.h
- include/CoreGen/CoreGenCodegen/NodeCodegen/ISACG.h
- src/CoreGenCodegen/CoreGenChiselCodegen.cpp
- src/CoreGenCodegen/CoreGenNodeCodegen.cpp
- src/CoreGenCodegen/NodeCodegen/CMakeLists.txt
- src/CoreGenCodegen/NodeCodegen/ISACG.cpp
- test/CodeGen/StoneCutterImpl/StoneCutterImpl_BasicRISCL1S10.yaml
- test/CodeGen/StoneCutterImpl/StoneCutterImpl_BasicRISCL2S9.yaml
- test/CodeGen/StoneCutterImpl/StoneCutterImpl_TEST2.yaml
- test/CodeGen/StoneCutterImpl/StoneCutterImpl_TEST3.yaml
- test/CodeGen/StoneCutterImpl/StoneCutterImpl_TEST4.yaml
- test/CodeGen/StoneCutterImpl/codegen_impl_test.sh
Full support for instruction bit pattern code generation in the Chisel codegen.  Added tests to include the BasicRISC design from the CoreGen tutorial material
> Full support for instruction bit pattern code generation

- README.md
updating the readme with contributing guidelines.
> updating readme formatting

- CMakeLists.txt
- include/CoreGen/CoreGenBackend/CoreGenPassMgr.h
- include/CoreGen/CoreGenBackend/Passes/Analysis/ASPSolverPass.h
- include/CoreGen/CoreGenBackend/Passes/Analysis/ConstrParser.h
- src/CGCLI/CGCLIMain.cpp
- src/CGCLI/CGCLIOpts.cpp
- src/SCComp/CMakeLists.txt
- src/thirdparty/clingo-5.3.0/libclingo/CMakeLists.txt
- src/thirdparty/clingo-5.3.0/libgringo/CMakeLists.txt
- src/thirdparty/clingo-5.3.0/libluaclingo/CMakeLists.txt
- src/thirdparty/clingo-5.3.0/libreify/CMakeLists.txt
This includes updates to the CMake build options for Clingo as well as one build dependency update for devtoolset-7-gcc-gc++ for Centos; fixes for Issue #115
> Fixes for RPM installation infrastructure

- include/CoreGen/CoreGenSigMap/CoreGenSigMap.h
- include/CoreGen/StoneCutter/Intrinsics/SCNeg.h
- include/CoreGen/StoneCutter/SCIntrinsics.h
- src/CoreGenSigMap/CoreGenSigMap.cpp
- src/SCSigV/SCSigV.cpp
- src/StoneCutter/Intrinsics/CMakeLists.txt
- src/StoneCutter/Intrinsics/SCNeg.cpp
- src/StoneCutter/SCChiselCodeGen.cpp
- src/StoneCutter/SCParser.cpp
- test/StoneCutter/OptParser/KnownPass/sc_optparser_test128.sc
- test/StoneCutter/Parser/KnownFail/sc_parser_test101_KF.sc
- test/StoneCutter/Parser/KnownFail/sc_parser_test102_KF.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test127.sc
- test/StoneCutter/SigMap/sc_sigmap_test_6.sc
adding negation intrinsic & better scsigv error handling
> adding negation intrinsic & better scsigv error handling  

- include/CoreGen/CoreGenBackend/Passes/Data/SpecDoc.h
- include/CoreGen/CoreGenBackend/Passes/Data/StatsPass.h
- include/CoreGen/CoreGenSigMap/SCSig.h
- include/CoreGen/StoneCutter/Passes/SCSigMap.h
- include/CoreGen/StoneCutter/SCChiselCodeGen.h
- include/CoreGen/StoneCutter/SCMsg.h
- include/CoreGen/StoneCutter/SCOpts.h
- include/CoreGen/StoneCutter/SCPerf.h
- include/CoreGen/StoneCutter/SCPipeInfo.h
- src/CoreGenBackend/CoreGenInstFormat.cpp
- src/CoreGenBackend/CoreGenYaml.cpp
- src/CoreGenBackend/Passes/Data/SpecDoc.cpp
- src/CoreGenBackend/Passes/Data/StatsPass.cpp
- src/CoreGenSigMap/CoreGenSigMap.cpp
- src/CoreGenSigMap/SCSig.cpp
- src/StoneCutter/CMakeLists.txt
- src/StoneCutter/Passes/SCSigMap.cpp
- src/StoneCutter/SCChiselCodeGen.cpp
- src/StoneCutter/SCMsg.cpp
- src/StoneCutter/SCOpts.cpp
- src/StoneCutter/SCPass.cpp
- src/StoneCutter/SCPerf.cpp
- src/StoneCutter/SCPipeInfo.cpp
- test/StoneCutter/CodeGen/KnownPass/sc_codegen_test.sh
- test/StoneCutter/SCSigV/KnownFail/sc_sigv_test8_KF.yaml
- test/StoneCutter/SCSigV/KnownPass/sc_sigv_test5.yaml
Major updates to the SpecDoc, Stats, uOp emission and several small bug fixes
Fixed issues: 
- Issue #157 
- Issue #162 
- Issue #163 
- Issue #164 
- Issue #165
> Major Updates to SpecDoc, Stats and Small Bug Fixes

- .gitignore
- README.md
- include/CoreGen/CoreGenBackend/CoreGenBackend.h
- include/CoreGen/CoreGenBackend/CoreGenCache.h
- include/CoreGen/CoreGenBackend/CoreGenInst.h
- include/CoreGen/CoreGenBackend/Passes/Analysis/EncodingCollisionPass.h
- include/CoreGen/CoreGenBackend/Passes/Data/SpecDoc.h
- include/CoreGen/CoreGenBackend/Passes/Data/StatsPass.h
- include/CoreGen/StoneCutter/SCParser.h
- src/CoreGenBackend/CoreGenBackend.cpp
- src/CoreGenBackend/CoreGenCache.cpp
- src/CoreGenBackend/CoreGenInst.cpp
- src/CoreGenBackend/CoreGenYaml.cpp
- src/CoreGenBackend/Passes/Analysis/CacheLevelPass.cpp
- src/CoreGenBackend/Passes/Analysis/EncodingCollisionPass.cpp
- src/CoreGenBackend/Passes/Data/SpecDoc.cpp
- src/CoreGenBackend/Passes/Data/StatsPass.cpp
- test/CodeGen/StoneCutterImpl/codegen_impl_test.sh
...and bugs found in initial SoC prototyping
> Merging up changes to handle latest GUI updates

- include/CoreGen/CoreGenBackend/CoreGenPseudoInst.h
- src/CoreGenBackend/CoreGenPseudoInst.cpp
- src/CoreGenBackend/CoreGenYaml.cpp
- test/Yaml/Reader/TEST86.yaml
- test/Yaml/Reader/yaml_reader_test_86.cpp
- test/Yaml/Writer/yaml_test_80.cpp
Merging up syntax mnemonics for PseudoInsts
> Merging up syntax mnemonics for PseudoInsts

- include/CoreGen/CoreGenBackend/CoreGenNode.h
- include/CoreGen/CoreGenBackend/Passes/Analysis/EncodingCollisionPass.h
- src/CoreGenBackend/CoreGenInst.cpp
- src/CoreGenBackend/CoreGenNode.cpp
- src/CoreGenBackend/CoreGenPseudoInst.cpp
- src/CoreGenBackend/CoreGenYaml.cpp
- src/CoreGenBackend/Passes/Analysis/EncodingCollisionPass.cpp
- src/CoreGenBackend/Passes/Data/SpecDoc.cpp
- test/Yaml/Reader/TEST88.yaml
- test/Yaml/Reader/yaml_reader_test_88.cpp
- test/Yaml/Writer/yaml_test_80.cpp
- test/Yaml/Writer/yaml_test_81.cpp
this is a critical fix for opening/closing yaml files
> Fix for opening/closing Yaml files

- include/CoreGen/CoreGenBackend/CoreGenBackend.h
- include/CoreGen/CoreGenBackend/Passes/Data/StatsPass.h
- src/CoreGenBackend/CoreGenComm.cpp
- src/CoreGenBackend/CoreGenCore.cpp
- src/CoreGenBackend/CoreGenInst.cpp
- src/CoreGenBackend/CoreGenInstFormat.cpp
- src/CoreGenBackend/CoreGenNode.cpp
- src/CoreGenBackend/CoreGenPseudoInst.cpp
- src/CoreGenBackend/CoreGenYaml.cpp
- src/CoreGenBackend/Passes/Data/StatsPass.cpp
- test/Yaml/Reader/TEST89.yaml
- test/Yaml/Reader/TEST90.yaml
- test/Yaml/Reader/TEST91.yaml
- test/Yaml/Reader/TEST92.yaml
- test/Yaml/Reader/TEST93.yaml
- test/Yaml/Reader/TEST94.yaml
- test/Yaml/Reader/yaml_reader_test_89.cpp
- test/Yaml/Reader/yaml_reader_test_90.cpp
- test/Yaml/Reader/yaml_reader_test_91.cpp
- test/Yaml/Reader/yaml_reader_test_92.cpp
- test/Yaml/Reader/yaml_reader_test_93.cpp
- test/Yaml/Reader/yaml_reader_test_94.cpp
- test/Yaml/Writer/yaml_test_82.cpp
- test/Yaml/Writer/yaml_test_83.cpp
- test/Yaml/Writer/yaml_test_84.cpp
- test/Yaml/Writer/yaml_test_85.cpp
- test/Yaml/Writer/yaml_test_86.cpp
- test/Yaml/Writer/yaml_test_87.cpp
merging up bug fixes for UI infrastructure
> merging up bug fixes for UI infrastructure

- README.md
> Archive devel

- src/CoreGenArchive/CoreGenArchive.cpp
- test/Archive/archive_test_8.yaml
> fix for failed tgz

- README.md
- include/CoreGen/StoneCutter/SCOpts.h
- include/CoreGen/StoneCutter/SCParser.h
- src/StoneCutter/SCLLCodeGen.cpp
> merging updates for LLVM 7/8

- src/StoneCutter/SCParser.cpp
fixing build failure on ubuntu 16.04
> fixing build failure on ubuntu 16.04

- include/CoreGen/StoneCutter/SCPass.h
- src/StoneCutter/SCParser.cpp
- src/StoneCutter/SCPass.cpp
these functions operate on Function and Instruction objects.
> Adding functions to retrieve pipeline attributes and metadata

- include/CoreGen/CoreGenCodegen/CoreGenCodegen.h
- include/CoreGen/StoneCutter/SCParser.h
- include/CoreGen/StoneCutter/SCUtil.h
- src/CoreGenCodegen/CoreGenCodegen.cpp
- src/StoneCutter/SCParser.cpp
- test/StoneCutter/OptParser/KnownPass/sc_optparser_test139.sc
- test/StoneCutter/OptParser/KnownPass/sc_optparser_test140.sc
- test/StoneCutter/Parser/KnownFail/sc_parser_test107_KF.sc
- test/StoneCutter/Parser/KnownFail/sc_parser_test108_KF.sc
- test/StoneCutter/Parser/KnownFail/sc_parser_test109_KF.sc
- test/StoneCutter/Parser/KnownFail/sc_parser_test110_KF.sc
- test/StoneCutter/Parser/KnownFail/sc_parser_test111_KF.sc
- test/StoneCutter/Parser/KnownFail/sc_parser_test112_KF.sc
- test/StoneCutter/Parser/KnownFail/sc_parser_test113_KF.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test137.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test138.sc
> Adding register attributes for all standard attributes

- include/CoreGen/CoreGenBackend/Passes/Analysis/SpadSafetyPass.h
- src/CoreGenBackend/Passes/Analysis/SpadSafetyPass.cpp
- test/DAG/IndividualPasses/KnownFail/TEST29.yaml
- test/DAG/IndividualPasses/KnownFail/TEST30.yaml
- test/DAG/IndividualPasses/KnownFail/ind_pass_test29.cpp
- test/DAG/IndividualPasses/KnownFail/ind_pass_test30.cpp
> adding tests for port continuity in the scratchpad interfaces

- include/CoreGen/CoreGenSigMap/CMakeLists.txt
- include/CoreGen/CoreGenSigMap/CoreGenSigMap.h
- include/CoreGen/CoreGenSigMap/Passes/CMakeLists.txt
- include/CoreGen/CoreGenSigMap/Passes/SMLegalizeSigMap.h
- include/CoreGen/CoreGenSigMap/SMPass.h
- include/CoreGen/CoreGenSigMap/SMPasses.h
- src/CoreGenBackend/CoreGenYaml.cpp
- src/CoreGenSigMap/CMakeLists.txt
- src/CoreGenSigMap/CoreGenSigMap.cpp
- src/CoreGenSigMap/Passes/CMakeLists.txt
- src/CoreGenSigMap/Passes/SMLegalizeSigMap.cpp
- src/SCSigV/SCSigV.cpp
- src/StoneCutter/Passes/SCSigMap.cpp
- test/StoneCutter/SCSigV/KnownFail/sc_sigv_test10_KF.yaml
- test/StoneCutter/SCSigV/KnownFail/sc_sigv_test11_KF.yaml
- test/StoneCutter/SCSigV/KnownFail/sc_sigv_test12_KF.yaml
- test/StoneCutter/SCSigV/KnownFail/sc_sigv_test9_KF.yaml
These are fixes for #158 and #178
> Adding SCSigMap Passes and LegalizeSigMap pass

- include/CoreGen/CoreGenBackend/CoreGenMCtrl.h
- src/CoreGenBackend/CoreGenMCtrl.cpp
- src/CoreGenBackend/CoreGenYaml.cpp
- test/Yaml/Reader/MissingData/TEST46.yaml
- test/Yaml/Reader/MissingData/yaml_reader_missingdata_46.cpp
- test/Yaml/Reader/TEST96.yaml
- test/Yaml/Reader/yaml_reader_test_96.cpp
- test/Yaml/Writer/yaml_test_88.cpp
- test/Yaml/Writer/yaml_test_89.cpp
- test/Yaml/Writer/yaml_test_90.cpp
Fix for Issue #2; need to add text for support in the Yaml IR spec
> adding memory ordering parameters for memory controllers

- include/CoreGen/StoneCutter/SCChiselCodeGen.h
- include/CoreGen/StoneCutter/SCExec.h
- include/CoreGen/StoneCutter/SCOpts.h
- include/CoreGen/StoneCutter/SCPass.h
- src/StoneCutter/Passes/SCFieldIO.cpp
- src/StoneCutter/Passes/SCIOWarn.cpp
- src/StoneCutter/Passes/SCInstArg.cpp
- src/StoneCutter/Passes/SCInstFormat.cpp
- src/StoneCutter/Passes/SCPipeBuilder.cpp
- src/StoneCutter/Passes/SCSigMap.cpp
- src/StoneCutter/SCChiselCodeGen.cpp
- src/StoneCutter/SCExec.cpp
- src/StoneCutter/SCOpts.cpp
- src/StoneCutter/SCPass.cpp
- test/StoneCutter/CLI/sccomp_disable_all_sc.sc
- test/StoneCutter/CLI/sccomp_disable_all_sc.sh
- test/StoneCutter/CLI/sccomp_enable_all_sc.sc
- test/StoneCutter/CLI/sccomp_enable_all_sc.sh
- test/StoneCutter/CLI/sccomp_list_sc_passes.sh
- test/StoneCutter/CLI/sccomp_set_all_sc.sc
- test/StoneCutter/CLI/sccomp_set_all_sc.sh
> Adding StoneCutter pass enable/disable/options

- src/StoneCutter/SCChiselCodeGen.cpp
adding one more fix for Issue #101
> adding one more fix for Issue #101

- include/CoreGen/StoneCutter/SCChiselCodeGen.h
- include/CoreGen/StoneCutter/SCOpts.h
- src/CoreGenSigMap/Passes/SMLegalizeSigMap.cpp
- src/StoneCutter/Passes/SCIOWarn.cpp
- src/StoneCutter/Passes/SCSigMap.cpp
- src/StoneCutter/SCChiselCodeGen.cpp
- src/StoneCutter/SCOpts.cpp
- src/StoneCutter/SCParser.cpp
- src/StoneCutter/SCPass.cpp
- test/StoneCutter/CLI/sccomp_sigmap.sh
- test/StoneCutter/SigMap/sc_sigmap_test.sh
- test/StoneCutter/SigMap/sc_sigmap_test7.sc
- test/StoneCutter/SigMap/sc_sigmap_test8.sc
Fix for Issue #225 and Issue #226
> Fix for Issues #225 and #226

- README.md
- src/StoneCutter/SCParser.cpp
- test/StoneCutter/OptParser/KnownPass/sc_optparser_test11.sc
- test/StoneCutter/OptParser/KnownPass/sc_optparser_test12.sc
- test/StoneCutter/OptParser/KnownPass/sc_optparser_test8.sc
- test/StoneCutter/Parser/KnownPass/MultiFile/sc_parser_test8.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test11.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test12.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test8.sc
Forcing 'for' loops to require a step value.  Also removing build support for Arch Linux
> enforcing better syntax standards for 'for' loops

- README.md
- include/CoreGen/StoneCutter/SCChiselCodeGen.h
- include/CoreGen/StoneCutter/SCOpts.h
- src/CoreGenSigMap/Passes/SMLegalizeSigMap.cpp
- src/StoneCutter/Passes/SCIOWarn.cpp
- src/StoneCutter/Passes/SCSigMap.cpp
- src/StoneCutter/SCChiselCodeGen.cpp
- src/StoneCutter/SCOpts.cpp
- src/StoneCutter/SCParser.cpp
- src/StoneCutter/SCPass.cpp
- test/StoneCutter/CLI/sccomp_sigmap.sh
- test/StoneCutter/OptParser/KnownPass/sc_optparser_test11.sc
- test/StoneCutter/OptParser/KnownPass/sc_optparser_test12.sc
- test/StoneCutter/OptParser/KnownPass/sc_optparser_test8.sc
- test/StoneCutter/Parser/KnownPass/MultiFile/sc_parser_test8.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test11.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test12.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test8.sc
- test/StoneCutter/SigMap/sc_sigmap_test.sh
- test/StoneCutter/SigMap/sc_sigmap_test7.sc
- test/StoneCutter/SigMap/sc_sigmap_test8.sc
Fixing 'for' loop syntax and removing Arch linux from build rules
> Fixing 'for' loop syntax and removing Arch linux from build rules

- include/CoreGen/CoreGenBackend/CoreGenRegClass.h
- include/CoreGen/CoreGenBackend/Passes/Analysis/RegClassSafetyPass.h
- src/CoreGenBackend/CoreGenRegClass.cpp
- src/CoreGenBackend/CoreGenYaml.cpp
- src/CoreGenBackend/Passes/Analysis/RegClassSafetyPass.cpp
- src/CoreGenCodegen/NodeCodegen/RegClassCG.cpp
- test/DAG/IndividualPasses/KnownFail/TEST31.yaml
- test/DAG/IndividualPasses/KnownFail/TEST32.yaml
- test/DAG/IndividualPasses/KnownFail/ind_pass_test31.cpp
- test/DAG/IndividualPasses/KnownFail/ind_pass_test32.cpp
- test/Yaml/Reader/TEST97.yaml
- test/Yaml/Reader/yaml_reader_test_97.cpp
- test/Yaml/Writer/yaml_test_91.cpp
Adding read and write ports to register class definitions; adding associated tests; updated IR Spec in https://github.com/opensocsysarch/CoreGenIRSpec/commit/3f04a653593f84af279104fff0a41b534e9fc782.
> Adding RegisterClass read and write ports

- include/CoreGen/CoreGenPlugin/CoreGenPluginImpl.h
- src/CoreGenPlugin/CoreGenPluginImpl.cpp
Support for new codegen functions, virtual codegen functions and initialization functions
> Fix for Issues #238 and #239

- include/CoreGen/CoreGenBackend/CoreGenPlugin.h
- include/CoreGen/CoreGenPlugin/CoreGenPluginImpl.h
- src/CoreGen-Config/CoreGen-Config.cpp
- src/CoreGenBackend/CoreGenPlugin.cpp
- src/CoreGenPlugin/CoreGenPluginImpl.cpp
- test/Config/coregen-config-test.sh
Merging fix for Issue #242; updating plugin codegen arguments; fixing include path arguments
> Merging fix for Issue #242

- archive/master.yaml
- include/CoreGen/CoreGenArchive/CoreGenArchive.h
- include/CoreGen/CoreGenBackend/CoreGenBackend.h
- include/CoreGen/CoreGenBackend/CoreGenUtil.h
- include/CoreGen/CoreGenCodegen/CoreGenCodegen.h
- include/CoreGen/CoreGenCodegen/CoreGenLLVMCodegen.h
- src/CGCLI/CGCLIMain.cpp
- src/CGCLI/CGCLIOpts.cpp
- src/CGCLI/CGCLIOpts.h
- src/CoreGenBackend/CoreGenBackend.cpp
- src/CoreGenCodegen/CMakeLists.txt
- src/CoreGenCodegen/CoreGenCodegen.cpp
- src/CoreGenCodegen/CoreGenLLVMCodegen.cpp
> Partial merge of LLVM codegen

- include/CoreGen/CoreGenBackend/CoreGenPlugin.h
- include/CoreGen/CoreGenCodegen/CoreGenChiselCodegen.h
- include/CoreGen/CoreGenCodegen/CoreGenNodeCodegen.h
- include/CoreGen/CoreGenCodegen/CoreGenNodeCodegens.h
- include/CoreGen/CoreGenCodegen/NodeCodegen/CacheCG.h
- src/CoreGenBackend/CoreGenBackend.cpp
- src/CoreGenBackend/CoreGenDAG.cpp
- src/CoreGenBackend/CoreGenPlugin.cpp
- src/CoreGenCodegen/CoreGenChiselCodegen.cpp
- src/CoreGenCodegen/NodeCodegen/CMakeLists.txt
- src/CoreGenCodegen/NodeCodegen/CacheCG.cpp
Merging changes to backend codegen in order to assist with plugin implementation
> Merging changes to backend codegen in order to assist with plugin implementation

- include/CoreGen/CoreGenBackend/CoreGenRegClass.h
- include/CoreGen/CoreGenCodegen/CoreGenLLVMCodegen.h
- src/CoreGenBackend/CoreGenRegClass.cpp
- src/CoreGenCodegen/CoreGenLLVMCodegen.cpp
Instruction codegen from LLVMCG
> Instruction Codegen

- include/CoreGen/CoreGenCodegen/LLVMCodegen/CMakeLists.txt
- include/CoreGen/CoreGenCodegen/LLVMCodegen/LLVM801CG.h
> adding missing headers

- include/CoreGen/CoreGenSigMap/CoreGenSigMap.h
- include/CoreGen/CoreGenSigMap/SCSig.h
- include/CoreGen/StoneCutter/Passes/SCPipeBuilder.h
- include/CoreGen/StoneCutter/SCOpts.h
- include/CoreGen/StoneCutter/SCPass.h
- src/CoreGenSigMap/CoreGenSigMap.cpp
- src/CoreGenSigMap/SCSig.cpp
- src/StoneCutter/Passes/SCInstArg.cpp
- src/StoneCutter/Passes/SCPipeBuilder.cpp
- src/StoneCutter/SCChiselCodeGen.cpp
- src/StoneCutter/SCOpts.cpp
- src/StoneCutter/SCParser.cpp
- src/StoneCutter/SCPass.cpp
- test/StoneCutter/CLI/sccomp_O1.sh
- test/StoneCutter/CLI/sccomp_O1_Pipeline.sh
- test/StoneCutter/CLI/sccomp_O1_Pipeline_Area.sh
- test/StoneCutter/CLI/sccomp_O1_Pipeline_Perf.sh
- test/StoneCutter/CLI/sccomp_O2.sh
- test/StoneCutter/CLI/sccomp_O2_Pipeline.sh
- test/StoneCutter/CLI/sccomp_O2_Pipeline_Area.sh
- test/StoneCutter/CLI/sccomp_O2_Pipeline_Perf.sh
- test/StoneCutter/CLI/sccomp_O3.sh
- test/StoneCutter/CLI/sccomp_O3_Pipeline.sh
- test/StoneCutter/CLI/sccomp_O3_Pipeline_Area.sh
- test/StoneCutter/CLI/sccomp_O3_Pipeline_Perf.sh
- test/StoneCutter/SCSigV/KnownFail/sc_sigv_test.sh
- test/StoneCutter/SCSigV/KnownFail/sc_sigv_test8_KF.yaml
- test/StoneCutter/SCSigV/KnownPass/sc_sigv_test5.yaml
- test/StoneCutter/SCSigV/KnownPass/sc_sigv_test6.yaml
- test/StoneCutter/SCSigV/KnownPass/sc_sigv_test7.yaml
This adds the bulk of the initial SCPipeBuilder pipelining pass and initial command line tests
> Merging SCPipeBuilder pipelining pass

- include/CoreGen/CoreGenCodegen/CoreGenLLVMCodegen.h
- include/CoreGen/CoreGenCodegen/LLVMCodegen/LLVM801CG.h
- src/CoreGenCodegen/CoreGenLLVMCodegen.cpp
- src/CoreGenCodegen/LLVMCodegen/LLVM801CG.cpp
Full LLVMCodegen Impl for 8.0.1
> Full LLVMCodegen Impl for 8.0.1

- include/CoreGen/CoreGenBackend/CoreGenPlugin.h
- include/CoreGen/CoreGenCodegen/CoreGenChiselCodegen.h
- include/CoreGen/CoreGenCodegen/CoreGenChiselParms.h
- include/CoreGen/CoreGenCodegen/CoreGenNodeCodegen.h
- include/CoreGen/CoreGenCodegen/NodeCodegen/DPathCG.h
- include/CoreGen/CoreGenCodegen/NodeCodegen/PluginCG.h
- include/CoreGen/CoreGenPlugin/CoreGenPluginImpl.h
- src/CoreGenBackend/CoreGenPlugin.cpp
- src/CoreGenCodegen/CoreGenChiselCodegen.cpp
- src/CoreGenCodegen/NodeCodegen/PluginCG.cpp
Changes to handle Open2C plugin
> Changes to handle Open2C plugin

- README.md
- include/CoreGen/CoreGenBackend/CoreGenExt.h
- include/CoreGen/StoneCutter/Passes/SCMetadataAdjust.h
- include/CoreGen/StoneCutter/Passes/SCPipeBuilder.h
- include/CoreGen/StoneCutter/Passes/SCSigMap.h
- include/CoreGen/StoneCutter/SCOpts.h
- include/CoreGen/StoneCutter/SCPass.h
- include/CoreGen/StoneCutter/SCPasses.h
- src/CoreGenBackend/CoreGenExt.cpp
- src/CoreGenBackend/CoreGenYaml.cpp
- src/CoreGenSigMap/Passes/SMLegalizeSigMap.cpp
- src/StoneCutter/Passes/CMakeLists.txt
- src/StoneCutter/Passes/SCMetadataAdjust.cpp
- src/StoneCutter/Passes/SCPipeBuilder.cpp
- src/StoneCutter/Passes/SCSigMap.cpp
- src/StoneCutter/SCChiselCodeGen.cpp
- src/StoneCutter/SCOpts.cpp
- src/StoneCutter/SCParser.cpp
- src/StoneCutter/SCPass.cpp
- test/StoneCutter/CLI/opt_O3_Metadata.sc
- test/StoneCutter/CLI/sccomp_O3_Metadata.sh
merging latest bug fixes up to master
> Merging latest bug fixes up to master

- include/CoreGen/Poar/Accumulators/PoarALUCPathAccum.h
- include/CoreGen/Poar/Accumulators/PoarALUDPathAccum.h
- include/CoreGen/Poar/Accumulators/PoarDPathAccum.h
- include/CoreGen/Poar/Accumulators/PoarROMAccum.h
- include/CoreGen/Poar/PoarAccum.h
- include/CoreGen/Poar/PoarAccums.h
- include/CoreGen/Poar/PoarConfig.h
- src/Poar/Accumulators/CMakeLists.txt
- src/Poar/Accumulators/PoarALUCPathAccum.cpp
- src/Poar/Accumulators/PoarALUDPathAccum.cpp
- src/Poar/Accumulators/PoarDPathAccum.cpp
- src/Poar/Accumulators/PoarROMAccum.cpp
- src/Poar/PoarConfig.cpp
- src/Poar/PoarData.cpp
merging up latest changes to include design data paths
> Power area

- include/CoreGen/StoneCutter/SCUtil.h
- src/StoneCutter/SCParser.cpp
- test/StoneCutter/Parser/KnownFail/sc_parser_test121_KF.sc
- test/StoneCutter/Parser/KnownFail/sc_parser_test122_KF.sc
- test/StoneCutter/Parser/KnownFail/sc_parser_test123_KF.sc
- test/StoneCutter/Parser/KnownFail/sc_parser_test124_KF.sc
- test/StoneCutter/Parser/KnownFail/sc_parser_test125_KF.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test147.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test148.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test149.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test150.sc
- Added SCParser support for vectors and matrix within StoneCutter & testing for all
- Added matrix and vector attributes to the IR
> Rkabrick/Issues[307, 308, 312, 313]

- src/StoneCutter/SCParser.cpp
Added vector and mat expansion in the same way RegClass vec and mats are handled.
ie. 
- u64 VAR<3> -> VAR, VAR_0, VAR_1, VAR_2
- u64 VAR<2, 2> VAR, VAR_r0, VAR_r1, VAR_c1, VAR_c2, VAR_diag (becuase it's square), VAR_0_0, VAR_0_1, ... etc.
> Added variable expansion for vectors and matrices

- test/StoneCutter/Parser/KnownFail/sc_parser_test126_KF.sc
- test/StoneCutter/Parser/KnownFail/sc_parser_test127_KF.sc
- test/StoneCutter/Parser/KnownFail/sc_parser_test128_KF.sc
- test/StoneCutter/Parser/KnownFail/sc_parser_test129_KF.sc
- test/StoneCutter/Parser/KnownFail/sc_parser_test130_KF.sc
- test/StoneCutter/Parser/KnownFail/sc_parser_test131_KF.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test151.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test152.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test153.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test154.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test155.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test156.sc
- test/StoneCutter/Parser/KnownPass/sc_parser_test157.sc
Added tests for the vector and matrix expansion for variables
> Added tests for vec/mat variable expansion

- include/CoreGen/StoneCutter/SCParser.h
- src/StoneCutter/SCParser.cpp
Just showing the preliminary work on the LocalContainers logic so that we can move forward with getting proper upstream handling of vector code gen
> Prelim LocalContainers Logic (No need to accept)

- src/StoneCutter/SCParser.cpp
Merging up fix for Issue #360 This reverts the removed code.
> fixing line numbering; Issue #360

- README.md
- include/CoreGen/CoreGenSigMap/CoreGenSigMap.h
- include/CoreGen/StoneCutter/Passes/SCVLIWPipeBuilder.h
- include/CoreGen/StoneCutter/SCExec.h
- include/CoreGen/StoneCutter/SCParser.h
- include/CoreGen/StoneCutter/SCPass.h
- src/CoreGenSigMap/CoreGenSigMap.cpp
- src/SCSigV/SCSigV.cpp
- src/StoneCutter/Passes/SCInstArg.cpp
- src/StoneCutter/Passes/SCPipeBuilder.cpp
- src/StoneCutter/Passes/SCSigMap.cpp
- src/StoneCutter/Passes/SCVLIWPipeBuilder.cpp
- src/StoneCutter/SCExec.cpp
- src/StoneCutter/SCParser.cpp
- src/StoneCutter/SCPass.cpp
- test/StoneCutter/CMakeLists.txt
- test/StoneCutter/Pipeliner/CMakeLists.txt
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_arg_KF.sc
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_arg_KF.sh
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_basic_1.sc
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_basic_1.sh
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_basic_2.sc
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_basic_2.sh
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_in_KF.sc
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_in_KF.sh
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_out_KF.sc
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_out_KF.sh
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_stage_KF.sc
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_stage_KF.sh
Merging initial VLIW changes up to devel
> Merging initial VLIW changes up to devel

- README.md
- include/CoreGen/CoreGenSigMap/CoreGenSigMap.h
- include/CoreGen/StoneCutter/Passes/SCVLIWPipeBuilder.h
- include/CoreGen/StoneCutter/SCExec.h
- include/CoreGen/StoneCutter/SCParser.h
- include/CoreGen/StoneCutter/SCPass.h
- src/CoreGenSigMap/CoreGenSigMap.cpp
- src/SCSigV/SCSigV.cpp
- src/StoneCutter/Passes/SCInstArg.cpp
- src/StoneCutter/Passes/SCPipeBuilder.cpp
- src/StoneCutter/Passes/SCSigMap.cpp
- src/StoneCutter/Passes/SCVLIWPipeBuilder.cpp
- src/StoneCutter/SCExec.cpp
- src/StoneCutter/SCParser.cpp
- src/StoneCutter/SCPass.cpp
- test/StoneCutter/CMakeLists.txt
- test/StoneCutter/Pipeliner/CMakeLists.txt
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_arg_KF.sc
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_arg_KF.sh
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_basic_1.sc
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_basic_1.sh
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_basic_2.sc
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_basic_2.sh
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_in_KF.sc
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_in_KF.sh
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_out_KF.sc
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_out_KF.sh
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_stage_KF.sc
- test/StoneCutter/Pipeliner/sc_vliw_pipeline_stage_KF.sh
re-merging vliw changes up to devel
> re-merging vliw changes up to devel

- README.md
- include/CoreGen/CoreGenBackend/CoreGenBackend.h
- include/CoreGen/CoreGenBackend/CoreGenDAG.h
- include/CoreGen/CoreGenBackend/CoreGenNode.h
- include/CoreGen/CoreGenBackend/CoreGenNodes.h
- include/CoreGen/CoreGenBackend/CoreGenVLIWStage.h
- include/CoreGen/CoreGenBackend/CoreGenYaml.h
- include/CoreGen/CoreGenBackend/Passes/Analysis/VLIWSafetyPass.h
- include/CoreGen/CoreGenBackend/Passes/CoreGenPasses.h
- src/CoreGenBackend/CMakeLists.txt
- src/CoreGenBackend/CoreGenBackend.cpp
- src/CoreGenBackend/CoreGenPassMgr.cpp
- src/CoreGenBackend/CoreGenReg.cpp
- src/CoreGenBackend/CoreGenVLIWStage.cpp
- src/CoreGenBackend/CoreGenYaml.cpp
- src/CoreGenBackend/Passes/Analysis/CMakeLists.txt
- src/CoreGenBackend/Passes/Analysis/VLIWSafetyPass.cpp
- src/CoreGenCodegen/CoreGenCodegen.cpp
- src/StoneCutter/Passes/SCFieldIO.cpp
- src/StoneCutter/SCParser.cpp
- test/Yaml/Reader/TEST110.yaml
- test/Yaml/Reader/TEST111.yaml
- test/Yaml/Reader/yaml_reader_test_110.cpp
- test/Yaml/Reader/yaml_reader_test_111.cpp
- test/Yaml/Writer/yaml_test_93.cpp
- test/Yaml/Writer/yaml_test_94.cpp
Adding new functionality for VLIWStage nodes in CoreGen IR
> Adding new functionality for VLIWStage nodes in CoreGen IR

- include/CoreGen/StoneCutter/Passes/SCSigMap.h
- src/CGCLI/CGCLIOpts.cpp
- src/StoneCutter/Passes/SCSigMap.cpp
- src/StoneCutter/SCOpts.cpp
- test/CGCLI/cgcli_opt_DisableMultiple.sh
- test/CGCLI/cgcli_opt_DisableOne.sh
This includes fixes for command line parsing of multiple pass names and switch instructions for lowering to signal maps
> Merging up fixes for command line parsing and switch instructions

- include/CoreGen/CoreGenPlugin/CoreGenPluginImpl.h
addig convenience macro to coregenpluginimpl
> addig convenience macro to coregenpluginimpl

- test/DHDT/CMakeLists.txt
> adding forgotten cmake file
